/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiBengkel;

import com.mysql.jdbc.Connection;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Unknown
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public mainMenu() {
        initComponents();
        load_tb_pelanggan();
        load_tb_spareparts();
        load_tb_penjualan();
        penjualan.setVisible(true);
        pelanggan.setVisible(false);
        spareparts.setVisible(false);
        penjualan_form.setVisible(true);
        pelanggan_form.setVisible(false);
        spareparts_form.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        penjualan_btn = new javax.swing.JLabel();
        spareparts_btn = new javax.swing.JLabel();
        pelanggan_btn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        table = new javax.swing.JPanel();
        penjualan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        penjualan_table = new javax.swing.JTable();
        pelanggan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pelanggan_table = new javax.swing.JTable();
        spareparts = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        spareparts_table = new javax.swing.JTable();
        form = new javax.swing.JPanel();
        penjualan_form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        noKTPJual = new javax.swing.JTextField();
        IDSPJual = new javax.swing.JTextField();
        jmlSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jualTambah = new javax.swing.JButton();
        jualEdit = new javax.swing.JButton();
        jualHapus = new javax.swing.JButton();
        IDJual = new javax.swing.JLabel();
        pelanggan_form = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNoKTP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNamaPel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        pelangganTambah = new javax.swing.JButton();
        pelangganEdit = new javax.swing.JButton();
        pelangganHapus = new javax.swing.JButton();
        spareparts_form = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNamaSP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtHargaSP = new javax.swing.JTextField();
        sparepartsTambah = new javax.swing.JButton();
        sparepartsEdit = new javax.swing.JButton();
        sparepartsHapus = new javax.swing.JButton();
        lblIDSP = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        header.setBackground(new java.awt.Color(41, 128, 185));
        header.setInheritsPopupMenu(true);

        penjualan_btn.setBackground(new java.awt.Color(52, 172, 224));
        penjualan_btn.setForeground(new java.awt.Color(255, 255, 255));
        penjualan_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penjualan_btn.setText("Penjualan");
        penjualan_btn.setOpaque(true);
        penjualan_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penjualan_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penjualan_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penjualan_btnMouseExited(evt);
            }
        });

        spareparts_btn.setBackground(new java.awt.Color(41, 128, 185));
        spareparts_btn.setForeground(new java.awt.Color(255, 255, 255));
        spareparts_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spareparts_btn.setText("Sparepart");
        spareparts_btn.setOpaque(true);
        spareparts_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spareparts_btnMouseClicked(evt);
            }
        });

        pelanggan_btn.setBackground(new java.awt.Color(41, 128, 185));
        pelanggan_btn.setForeground(new java.awt.Color(255, 255, 255));
        pelanggan_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pelanggan_btn.setText("Pelanggan");
        pelanggan_btn.setOpaque(true);
        pelanggan_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelanggan_btnMouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(52, 172, 224));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Bayar");
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Logo 2.png"))); // NOI18N
        jLabel14.setText("ESA BENGKEL");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(penjualan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(spareparts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pelanggan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penjualan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spareparts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelanggan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        body.setBackground(new java.awt.Color(52, 172, 224));

        table.setLayout(new java.awt.CardLayout());

        penjualan.setLayout(new javax.swing.BoxLayout(penjualan, javax.swing.BoxLayout.LINE_AXIS));

        penjualan_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        penjualan_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penjualan_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(penjualan_table);

        penjualan.add(jScrollPane1);

        table.add(penjualan, "card3");

        pelanggan.setLayout(new javax.swing.BoxLayout(pelanggan, javax.swing.BoxLayout.LINE_AXIS));

        pelanggan_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pelanggan_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelanggan_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pelanggan_table);

        pelanggan.add(jScrollPane2);

        table.add(pelanggan, "card3");

        spareparts.setLayout(new javax.swing.BoxLayout(spareparts, javax.swing.BoxLayout.LINE_AXIS));

        spareparts_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spareparts_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spareparts_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(spareparts_table);

        spareparts.add(jScrollPane3);

        table.add(spareparts, "card3");

        form.setLayout(new java.awt.CardLayout());

        penjualan_form.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Form Penjualan");

        jLabel3.setText("Jumlah Sparepart");

        jLabel4.setText("ID Sparepart");

        jLabel5.setText("No. KTP");

        jualTambah.setText("Tambah");
        jualTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualTambahActionPerformed(evt);
            }
        });

        jualEdit.setText("Edit");
        jualEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualEditActionPerformed(evt);
            }
        });

        jualHapus.setText("Hapus");
        jualHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualHapusActionPerformed(evt);
            }
        });

        IDJual.setForeground(new java.awt.Color(255, 255, 255));
        IDJual.setText("jLabel13");

        javax.swing.GroupLayout penjualan_formLayout = new javax.swing.GroupLayout(penjualan_form);
        penjualan_form.setLayout(penjualan_formLayout);
        penjualan_formLayout.setHorizontalGroup(
            penjualan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penjualan_formLayout.createSequentialGroup()
                .addGroup(penjualan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penjualan_formLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IDJual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(penjualan_formLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(penjualan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(penjualan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(noKTPJual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmlSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(IDSPJual, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(penjualan_formLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jualTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jualEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jualHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        penjualan_formLayout.setVerticalGroup(
            penjualan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penjualan_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(penjualan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDJual))
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noKTPJual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDSPJual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmlSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(penjualan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jualTambah)
                    .addComponent(jualEdit)
                    .addComponent(jualHapus))
                .addGap(27, 27, 27))
        );

        form.add(penjualan_form, "card2");

        pelanggan_form.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Form Pelanggan");

        jLabel7.setText("No. KTP");

        jLabel8.setText("Nama Lengkap");

        jLabel9.setText("No.HP");

        pelangganTambah.setText("Tambah");
        pelangganTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganTambahActionPerformed(evt);
            }
        });

        pelangganEdit.setText("Edit");
        pelangganEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganEditActionPerformed(evt);
            }
        });

        pelangganHapus.setText("Hapus");
        pelangganHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pelanggan_formLayout = new javax.swing.GroupLayout(pelanggan_form);
        pelanggan_form.setLayout(pelanggan_formLayout);
        pelanggan_formLayout.setHorizontalGroup(
            pelanggan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelanggan_formLayout.createSequentialGroup()
                .addGroup(pelanggan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pelanggan_formLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel6))
                    .addGroup(pelanggan_formLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pelanggan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(pelanggan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNoKTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtNamaPel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(pelanggan_formLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(pelangganTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pelangganEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pelangganHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pelanggan_formLayout.setVerticalGroup(
            pelanggan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelanggan_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaPel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pelanggan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pelangganTambah)
                    .addComponent(pelangganEdit)
                    .addComponent(pelangganHapus))
                .addGap(27, 27, 27))
        );

        form.add(pelanggan_form, "card2");

        spareparts_form.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Form Sparepart");

        jLabel11.setText("Nama Sparepart");

        jLabel12.setText("Harga");

        sparepartsTambah.setText("Tambah");
        sparepartsTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparepartsTambahActionPerformed(evt);
            }
        });

        sparepartsEdit.setText("Edit");
        sparepartsEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparepartsEditActionPerformed(evt);
            }
        });

        sparepartsHapus.setText("Hapus");
        sparepartsHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparepartsHapusActionPerformed(evt);
            }
        });

        lblIDSP.setForeground(new java.awt.Color(255, 255, 255));
        lblIDSP.setText("jLabel13");

        javax.swing.GroupLayout spareparts_formLayout = new javax.swing.GroupLayout(spareparts_form);
        spareparts_form.setLayout(spareparts_formLayout);
        spareparts_formLayout.setHorizontalGroup(
            spareparts_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spareparts_formLayout.createSequentialGroup()
                .addGroup(spareparts_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spareparts_formLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(spareparts_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtHargaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(spareparts_formLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(spareparts_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(spareparts_formLayout.createSequentialGroup()
                                .addComponent(lblIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel10))
                            .addGroup(spareparts_formLayout.createSequentialGroup()
                                .addComponent(sparepartsTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sparepartsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sparepartsHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        spareparts_formLayout.setVerticalGroup(
            spareparts_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spareparts_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spareparts_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblIDSP))
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHargaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(spareparts_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sparepartsTambah)
                    .addComponent(sparepartsEdit)
                    .addComponent(sparepartsHapus))
                .addGap(27, 27, 27))
        );

        form.add(spareparts_form, "card2");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelangganTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganTambahActionPerformed
        try {
            String sql = "INSERT INTO pelanggan VALUES ('" + txtNoKTP.getText() + "','" + txtNamaPel.getText() + "','" + txtNoHp.getText() + "')";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_tb_pelanggan();
        txtNoKTP.setText(null);
        txtNamaPel.setText(null);
        txtNoHp.setText(null);
    }//GEN-LAST:event_pelangganTambahActionPerformed

    private void pelanggan_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelanggan_tableMouseClicked
        int baris = pelanggan_table.rowAtPoint(evt.getPoint());
        String noKTP = pelanggan_table.getValueAt(baris, 1).toString();
        txtNoKTP.setText(noKTP);
        String namaPel = pelanggan_table.getValueAt(baris, 2).toString();
        txtNamaPel.setText(namaPel);
        String noHp = pelanggan_table.getValueAt(baris, 3).toString();
        txtNoHp.setText(noHp);
    }//GEN-LAST:event_pelanggan_tableMouseClicked

    private void pelangganEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganEditActionPerformed
        try {
            String sql = "UPDATE pelanggan SET no_ktp = '" + txtNoKTP.getText() + "', nama_pel = '" + txtNamaPel.getText() + "', no_hp = '" + txtNoHp.getText() + "' where no_ktp= '" + txtNoKTP.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Update " + e.getMessage());
        }
        load_tb_pelanggan();
        txtNoKTP.setText(null);
        txtNamaPel.setText(null);
        txtNoHp.setText(null);
    }//GEN-LAST:event_pelangganEditActionPerformed

    private void pelangganHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganHapusActionPerformed
        try {
            String sql = "delete from pelanggan where no_ktp='" + txtNoKTP.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_tb_pelanggan();
        txtNoKTP.setText(null);
        txtNamaPel.setText(null);
        txtNoHp.setText(null);
    }//GEN-LAST:event_pelangganHapusActionPerformed

    private void sparepartsTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparepartsTambahActionPerformed
        try {
            String sql = "INSERT INTO spareparts (nama_sp,harga) VALUES ('" + txtNamaSP.getText() + "','" + txtHargaSP.getText() + "')";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_tb_spareparts();
        txtNamaSP.setText(null);
        txtHargaSP.setText(null);
    }//GEN-LAST:event_sparepartsTambahActionPerformed

    private void spareparts_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spareparts_tableMouseClicked
        int baris = spareparts_table.rowAtPoint(evt.getPoint());
        String idSP = spareparts_table.getValueAt(baris, 0).toString();
        lblIDSP.setText(idSP);
        String namaSP = spareparts_table.getValueAt(baris, 1).toString();
        txtNamaSP.setText(namaSP);
        String hargaSP = spareparts_table.getValueAt(baris, 2).toString();
        txtHargaSP.setText(hargaSP);
    }//GEN-LAST:event_spareparts_tableMouseClicked

    private void sparepartsEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparepartsEditActionPerformed

        try {
            String sql = "UPDATE spareparts SET nama_sp = '" + txtNamaSP.getText() + "', nama_pel = '" + txtHargaSP.getText() + "' where id= '" + lblIDSP.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Update " + e.getMessage());
        }
        load_tb_spareparts();
        txtNamaSP.setText(null);
        txtHargaSP.setText(null);
    }//GEN-LAST:event_sparepartsEditActionPerformed

    private void sparepartsHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparepartsHapusActionPerformed
        try {
            String sql = "delete from spareparts where id='" + lblIDSP.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_tb_spareparts();
        txtNamaSP.setText(null);
        txtHargaSP.setText(null);
    }//GEN-LAST:event_sparepartsHapusActionPerformed

    private void jualTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualTambahActionPerformed
        try {
            String sql = "INSERT INTO penjualan (id_sp,no_ktp,jml_sp) VALUES ('" + IDSPJual.getText() + "','" + noKTPJual.getText() + "','" + jmlSP.getText() + "')";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            getIDJual();
            cariTotalHarga();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_tb_penjualan();
        noKTPJual.setText(null);
        IDSPJual.setText(null);
        jmlSP.setText(null);
        IDJual.setText(null);
    }//GEN-LAST:event_jualTambahActionPerformed

    private void jualEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualEditActionPerformed
        try {
            String sql = "UPDATE penjualan SET id_sp = '" + IDSPJual.getText() + "', no_ktp = '" + noKTPJual.getText() + "', jml_sp = '" + jmlSP.getText() + "' where id= '" + IDJual.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            cariTotalHarga();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Update " + e.getMessage());
        }
        load_tb_penjualan();
        noKTPJual.setText(null);
        IDSPJual.setText(null);
        jmlSP.setText(null);
        IDJual.setText(null);
    }//GEN-LAST:event_jualEditActionPerformed

    private void penjualan_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualan_tableMouseClicked
        int baris = penjualan_table.rowAtPoint(evt.getPoint());
        String id = penjualan_table.getValueAt(baris, 1).toString();
        IDJual.setText(id);
        String idSP = penjualan_table.getValueAt(baris, 2).toString();
        IDSPJual.setText(idSP);
        String noKTP = penjualan_table.getValueAt(baris, 3).toString();
        noKTPJual.setText(noKTP);
        String txtjmlSP = penjualan_table.getValueAt(baris, 4).toString();
        jmlSP.setText(txtjmlSP);
    }//GEN-LAST:event_penjualan_tableMouseClicked

    private void jualHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualHapusActionPerformed
        try {
            String sql = "delete from penjualan where id='" + IDJual.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_tb_penjualan();
        noKTPJual.setText(null);
        IDSPJual.setText(null);
        jmlSP.setText(null);
        IDJual.setText(null);
    }//GEN-LAST:event_jualHapusActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new bayarMenu().setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void pelanggan_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelanggan_btnMouseClicked
        penjualan.setVisible(false);
        pelanggan.setVisible(true);
        spareparts.setVisible(false);

        penjualan_form.setVisible(false);
        pelanggan_form.setVisible(true);
        spareparts_form.setVisible(false);

        hoverColor(pelanggan_btn);
        defaultColor(spareparts_btn);
        defaultColor(penjualan_btn);
    }//GEN-LAST:event_pelanggan_btnMouseClicked

    private void spareparts_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spareparts_btnMouseClicked
        penjualan.setVisible(false);
        pelanggan.setVisible(false);
        spareparts.setVisible(true);

        penjualan_form.setVisible(false);
        pelanggan_form.setVisible(false);
        spareparts_form.setVisible(true);

        hoverColor(spareparts_btn);
        defaultColor(penjualan_btn);
        defaultColor(pelanggan_btn);
    }//GEN-LAST:event_spareparts_btnMouseClicked

    private void penjualan_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualan_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_penjualan_btnMouseExited

    private void penjualan_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualan_btnMouseEntered

    }//GEN-LAST:event_penjualan_btnMouseEntered

    private void penjualan_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualan_btnMouseClicked
        penjualan.setVisible(true);
        pelanggan.setVisible(false);
        spareparts.setVisible(false);

        penjualan_form.setVisible(true);
        pelanggan_form.setVisible(false);
        spareparts_form.setVisible(false);

        hoverColor(penjualan_btn);
        defaultColor(spareparts_btn);
        defaultColor(pelanggan_btn);
    }//GEN-LAST:event_penjualan_btnMouseClicked
    private void cariTotalHarga() {
        try {
            String sql = "UPDATE penjualan SET total_byr=(select jml_sp * harga as value from penjualan, spareparts where penjualan.id='" + IDJual.getText() + "' and spareparts.id='" + IDSPJual.getText() + "') where id='" + IDJual.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void getIDJual() {
        try {
            String sql = "select * from penjualan where id_sp = '" + IDSPJual.getText() + "' and no_ktp = '" + noKTPJual.getText() + "' and jml_sp ='" + jmlSP.getText() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                IDJual.setText(res.getString("id"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void load_tb_penjualan() {
        penjualan_table.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("ID Sparepart");
        model.addColumn("No. KTP");
        model.addColumn("Jumlah Sparepart");
        model.addColumn("Total Bayar");

        try {
            int no = 1;
            String sql = "select * from penjualan";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
            penjualan_table.setModel(model);
        } catch (Exception e) {
        }
    }

    private void load_tb_spareparts() {
        spareparts_table.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Harga");

        try {
            String sql = "select * from spareparts";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
            }
            spareparts_table.setModel(model);
        } catch (Exception e) {
        }
    }

    private void load_tb_pelanggan() {
        pelanggan_table.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("No. KTP");
        model.addColumn("Nama");
        model.addColumn("No. HP");

        try {
            int no = 1;
            String sql = "select * from pelanggan";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3)});
            }
            pelanggan_table.setModel(model);
        } catch (Exception e) {
        }
    }

    public void defaultColor(javax.swing.JLabel lbl) {
        lbl.setBackground(new java.awt.Color(41, 128, 185));
    }

    public void hoverColor(javax.swing.JLabel lbl) {
        lbl.setBackground(new java.awt.Color(52, 172, 224));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDJual;
    private javax.swing.JTextField IDSPJual;
    private javax.swing.JPanel body;
    private javax.swing.JPanel form;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jmlSP;
    private javax.swing.JButton jualEdit;
    private javax.swing.JButton jualHapus;
    private javax.swing.JButton jualTambah;
    private javax.swing.JLabel lblIDSP;
    private javax.swing.JTextField noKTPJual;
    private javax.swing.JPanel pelanggan;
    private javax.swing.JButton pelangganEdit;
    private javax.swing.JButton pelangganHapus;
    private javax.swing.JButton pelangganTambah;
    private javax.swing.JLabel pelanggan_btn;
    private javax.swing.JPanel pelanggan_form;
    private javax.swing.JTable pelanggan_table;
    private javax.swing.JPanel penjualan;
    private javax.swing.JLabel penjualan_btn;
    private javax.swing.JPanel penjualan_form;
    private javax.swing.JTable penjualan_table;
    private javax.swing.JPanel spareparts;
    private javax.swing.JButton sparepartsEdit;
    private javax.swing.JButton sparepartsHapus;
    private javax.swing.JButton sparepartsTambah;
    private javax.swing.JLabel spareparts_btn;
    private javax.swing.JPanel spareparts_form;
    private javax.swing.JTable spareparts_table;
    private javax.swing.JPanel table;
    private javax.swing.JTextField txtHargaSP;
    private javax.swing.JTextField txtNamaPel;
    private javax.swing.JTextField txtNamaSP;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtNoKTP;
    // End of variables declaration//GEN-END:variables
}
